app:
  datasource:
    jdbc-url: jdbc:postgresql://192.168.8.104:5432/Store
    username: user
    password: password
    pool-size: 30

server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8443